apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-production
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: project/helm
    repoURL: 'https://github.com/marcondol/nd064_course_1'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-production.yaml
  project: default