namespace:
  name: sandbox
 
image:
  repository: marcondol/techtrends
  tag: v1.0.0
  pullpolicy: IfNotPresent

service:
  port: 5111
  targetPort: 3111  
  type: ClusterIP

replicaCount: 1

resources:
  cpu: 250m
  memory: 64Mi
  cpu_lim: 500m
  memory_lim: 128Mi